# Generated by Django 2.2 on 2020-01-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Название книги')),
                ('author', models.TextField(max_length=100, verbose_name='Автор книги')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('count', models.CharField(max_length=1000, verbose_name='Количество экземпляров')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('fullname', models.CharField(max_length=3000, verbose_name='ФИО сотрудника')),
                ('blocked', models.BooleanField(default=False, verbose_name='Статус сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='UseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField(max_length=100, verbose_name='Название книги')),
                ('book_author', models.TextField(max_length=100, verbose_name='Автор книги')),
                ('take_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации книги')),
                ('days', models.IntegerField(verbose_name='Количество дней')),
                ('return_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата возврата книги:')),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_bot.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_bot.User', verbose_name='Пользователь')),
            ],
        ),
    ]
