# Generated by Django 2.2 on 2020-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Статус сотрудника(Активен/Заблокирован)'),
        ),
    ]
