# Generated by Django 2.2 on 2020-01-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bot', '0002_auto_20200110_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uselog',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата книги:'),
        ),
    ]
