# Generated by Django 2.2 on 2020-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bot', '0003_auto_20200129_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uselog',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата возврата книги:'),
        ),
    ]
