# Generated by Django 2.2 on 2020-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_bot', '0004_auto_20200129_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uselog',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата книги:'),
        ),
    ]
